import { useLocale } from './LocaleContext';

const siteCopy = {
  zh: {
    homeBadge: '漫画视频工作流平台',
    homeTitle: 'PLATFORM',
    homeSubtitle: '上传 PDF 或 CBZ 漫画，并把它们变成带旁白的视频项目。',
    homeDescription: '从源文件上传开始，查看资产、创建任务、审核分镜，并逐步迭代成完整的漫画视频生产流水线。',
    homeOpenPlatform: '进入平台',
    homeFeaturesTitle: '核心能力',
    homeFeaturesDescription: '围绕漫画转视频流程搭建的前后端平台，优先强调可控、可替换、可落地。',
    featureFastTitle: '快速起步',
    featureFastDesc: '从上传漫画源文件到生成任务结果，尽快打通最短业务路径。',
    featureHdTitle: '统一资产流',
    featureHdDesc: '把画格图、分镜、音频、视频和中间元数据统一沉淀到项目中。',
    featureSmartTitle: '模型可替换',
    featureSmartDesc: '后续可以逐步替换 OCR、脚本、配音、视频模型，不绑死单一供应商。',
    featureAutoTitle: '面向生产二开',
    featureAutoDesc: '当前结构更适合做企业内网部署、任务编排和模型服务接入。',
    aboutTitleLine1: 'AI 驱动的',
    aboutTitleLine2: '漫画转视频平台',
    aboutBody1: '平台帮助漫画、条漫和网文团队把静态内容转成可编排的视频生产流程。',
    aboutBody2: '你可以从上传、解析、分镜、配音到成片一步步搭建自己的工作流。',
    statsVideos: '已生成视频',
    statsUsers: '活跃用户',
    statsRender: '平均渲染时间',
    statsSuccess: '成功率',
    ctaTitle: '准备开始你的漫画视频流程了吗？',
    ctaBody: '创建项目、上传 PDF 或 CBZ，并逐步查看解析、分镜、音频和视频结果。',
    contactTitle: '联系我们',
    contactSubtitle: '有部署、模型替换或二开合作需求，都可以直接沟通。',
    contactFaqTitle: '常见问题',
    contactDevTitle: '开发者',
    contactDevSubtitle: '如果你想合作、提需求或参与贡献，欢迎直接联系。',
    loginTitle: '登录平台',
    loginSubtitle: '使用邮箱验证码或 Google 登录。',
    loginWithGoogle: '使用 Google 登录',
    continueWithEmail: '使用邮箱继续',
    sending: '发送中…',
    verifying: '验证中…',
    verifyContinue: '验证并继续',
    backToEmail: '返回邮箱输入',
    enterCode: '输入 6 位验证码',
    authDisabledBanner: '认证当前不可用，请先配置前端 Supabase 环境变量。',
    termsPrefix: '继续即表示你同意我们的',
    terms: '服务条款',
    privacy: '隐私政策',
    meetDevelopers: '开发者团队',
    collaborationNote: '如需合作或共建，欢迎联系。',
  },
  en: {
    homeBadge: 'Comic Video Workflow Platform',
    homeTitle: 'PLATFORM',
    homeSubtitle: 'Upload PDF or CBZ comics and turn them into narrated video projects.',
    homeDescription: 'Start from source uploads, inspect assets, create jobs, review storyboards, and iterate toward a full comic-to-video production workflow.',
    homeOpenPlatform: 'Open Platform',
    homeFeaturesTitle: 'Core capabilities',
    homeFeaturesDescription: 'A full-stack platform built around the comic-to-video pipeline, optimized for control, replacement, and production delivery.',
    featureFastTitle: 'Fast start',
    featureFastDesc: 'Go from source upload to generated job results with the shortest usable product loop.',
    featureHdTitle: 'Unified asset flow',
    featureHdDesc: 'Keep panel images, storyboards, audio, video, and intermediate metadata inside one project workflow.',
    featureSmartTitle: 'Replaceable models',
    featureSmartDesc: 'Swap OCR, scripting, TTS, and video models incrementally without locking into one vendor.',
    featureAutoTitle: 'Production-oriented fork',
    featureAutoDesc: 'The current structure is designed for internal deployment, job orchestration, and model service integration.',
    aboutTitleLine1: 'AI-powered',
    aboutTitleLine2: 'comic-to-video platform',
    aboutBody1: 'The platform helps comic and webtoon teams convert static content into orchestrated video production workflows.',
    aboutBody2: 'You can build your own pipeline step by step, from upload and parsing to storyboard, voice, and final output.',
    statsVideos: 'Videos generated',
    statsUsers: 'Active users',
    statsRender: 'Avg render time',
    statsSuccess: 'Success rate',
    ctaTitle: 'Ready to start your comic video workflow?',
    ctaBody: 'Create a project, upload a PDF or CBZ, and inspect parsing, storyboard, audio, and video outputs step by step.',
    contactTitle: 'Contact us',
    contactSubtitle: 'Reach out if you need deployment help, model replacement support, or custom platform development.',
    contactFaqTitle: 'FAQ',
    contactDevTitle: 'Developers',
    contactDevSubtitle: 'If you want to collaborate, request features, or contribute, feel free to reach out.',
    loginTitle: 'Sign in to Platform',
    loginSubtitle: 'Use email OTP or Google sign-in.',
    loginWithGoogle: 'Continue with Google',
    continueWithEmail: 'Continue with Email',
    sending: 'Sending…',
    verifying: 'Verifying…',
    verifyContinue: 'Verify & Continue',
    backToEmail: 'Back to Email',
    enterCode: 'Enter 6-digit code',
    authDisabledBanner: 'Authentication is currently disabled. Configure frontend Supabase env vars first.',
    termsPrefix: 'By continuing, you agree to our',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    meetDevelopers: 'Meet the developers',
    collaborationNote: 'Feel free to reach out for collaboration or contributions.',
  },
};

export const useSiteText = () => {
  const { locale } = useLocale();
  return siteCopy[locale];
};
