import { useLocale } from './LocaleContext';

const siteCopy = {
  zh: {
    homeBadge: '漫画视频工作流平台',
    homeTitle: 'PLATFORM',
    homeSubtitle: '上传 PDF 或 CBZ 漫画，并把它们变成带旁白的视频项目。',
    homeDescription: '从源文件上传开始，查看资产、创建任务、审核分镜，并逐步迭代成完整的漫画视频生产流水线。',
    homeOpenPlatform: '进入平台',
    homeFeaturesTitle: '核心能力',
    homeFeaturesDescription: '围绕漫画转视频流程搭建的前后端平台，优先强调可控、可替换、可落地。',
    featureFastTitle: '快速起步',
    featureFastDesc: '从上传漫画源文件到生成任务结果，尽快打通最短业务路径。',
    featureHdTitle: '统一资产流',
    featureHdDesc: '把画格图、分镜、音频、视频和中间元数据统一沉淀到项目中。',
    featureSmartTitle: '模型可替换',
    featureSmartDesc: '后续可以逐步替换 OCR、脚本、配音、视频模型，不绑死单一供应商。',
    featureAutoTitle: '面向生产二开',
    featureAutoDesc: '当前结构更适合做企业内网部署、任务编排和模型服务接入。',
    aboutTitleLine1: 'AI 驱动的',
    aboutTitleLine2: '漫画转视频平台',
    aboutBody1: '平台帮助漫画、条漫和网文团队把静态内容转成可编排的视频生产流程。',
    aboutBody2: '你可以从上传、解析、分镜、配音到成片一步步搭建自己的工作流。',
    statsVideos: '已生成视频',
    statsUsers: '活跃用户',
    statsRender: '平均渲染时间',
    statsSuccess: '成功率',
    ctaTitle: '准备开始你的漫画视频流程了吗？',
    ctaBody: '创建项目、上传 PDF 或 CBZ，并逐步查看解析、分镜、音频和视频结果。',
    contactTitle: '联系我们',
    contactSubtitle: '有部署、模型替换或二开合作需求，都可以直接沟通。',
    contactFaqTitle: '常见问题',
    contactDevTitle: '开发者',
    contactDevSubtitle: '如果你想合作、提需求或参与贡献，欢迎直接联系。',
    loginTitle: '登录平台',
    loginSubtitle: '使用邮箱密码或 Google 登录。',
    loginWithGoogle: '使用 Google 登录',
    continueWithEmail: '使用邮箱密码登录',
    sending: '发送中…',
    verifying: '验证中…',
    verifyContinue: '登录并继续',
    backToEmail: '返回登录',
    enterCode: '输入账号密码',
    authDisabledBanner: '认证当前不可用，请先检查后端认证服务配置。',
    termsPrefix: '继续即表示你同意我们的',
    terms: '服务条款',
    privacy: '隐私政策',
    meetDevelopers: '开发者团队',
    collaborationNote: '如需合作或共建，欢迎联系。',
    registerTitle: '创建账号',
    registerSubtitle: '使用邮箱密码注册，或继续使用 Google。',
    emailLabel: '邮箱',
    emailPlaceholder: '输入你的邮箱',
    usernameOrEmailLabel: '邮箱或用户名',
    usernameOrEmailPlaceholder: '输入 admin、admin@local 或你的邮箱',
    passwordLabel: '密码',
    passwordPlaceholder: '输入你的密码',
    displayNameLabel: '显示名称',
    displayNamePlaceholder: '输入你的显示名称',
    loginButton: '登录',
    registerButton: '注册',
    signingIn: '登录中…',
    creatingAccount: '创建中…',
    loginSuccessTitle: '登录成功',
    loginSuccessBody: '正在跳转到平台…',
    registerSuccessTitle: '注册成功',
    registerSuccessBody: '账号已创建，正在进入平台…',
    loginGenericError: '登录失败，请稍后重试。',
    googleSignInError: 'Google 登录失败，请稍后重试。',
    loginMissingFields: '请填写邮箱和密码。',
    registerMissingName: '请填写显示名称。',
    noAccountYet: '还没有账号？',
    alreadyHaveAccount: '已经有账号了？',
    switchToRegister: '去注册',
    switchToLogin: '去登录',
    googleComingSoon: 'Google 登录稍后开放。',
    brandName: '平台',
    contactNameRequired: '请输入姓名',
    contactEmailRequired: '请输入邮箱',
    contactEmailInvalid: '邮箱格式不正确',
    contactMessageRequired: '请输入内容',
    contactSendFailed: '发送失败。',
    contactSendRetry: '发生错误，请稍后重试。',
    contactMessageSubject: '来自 Platform 网站的新消息',
    developerFrontendRole: '作者 / 维护者',
    developerBackendRole: '作者 / 维护者',
    faqConvertQuestion: '怎么把漫画转成视频？',
    faqConvertAnswer: '上传漫画 PDF 或 CBZ，选择合适的模式，然后点击生成视频。系统会自动完成解析、分镜和视频生成流程。',
    faqFormatsQuestion: '支持哪些文件格式？',
    faqFormatsAnswer: '当前支持 PDF 和 CBZ 作为漫画源文件，输出结果可以在平台内预览，并按任务产物下载。',
    faqPreviewQuestion: '生成后可以先预览吗？',
    faqPreviewAnswer: '可以。任务完成后，你可以在任务详情页查看分镜、资产以及最终视频结果。',
    faqLimitQuestion: '上传文件有大小限制吗？',
    faqLimitAnswer: '建议先使用体量较小的测试素材，便于更快验证上传、解析和生成链路。',
    faqInstallQuestion: '需要安装额外软件吗？',
    faqInstallAnswer: '前端无需额外安装；如果你要启用更完整的音视频能力，后端环境建议安装 ffmpeg 和 tesseract。',
    faqSafetyQuestion: '上传的数据安全吗？',
    faqSafetyAnswer: '当前平台定位为本地或内网部署，数据由你自己的运行环境和存储配置负责管理。',
  },
  en: {
    homeBadge: 'Comic Video Workflow Platform',
    homeTitle: 'PLATFORM',
    homeSubtitle: 'Upload PDF or CBZ comics and turn them into narrated video projects.',
    homeDescription: 'Start from source uploads, inspect assets, create jobs, review storyboards, and iterate toward a full comic-to-video production workflow.',
    homeOpenPlatform: 'Open Platform',
    homeFeaturesTitle: 'Core capabilities',
    homeFeaturesDescription: 'A full-stack platform built around the comic-to-video pipeline, optimized for control, replacement, and production delivery.',
    featureFastTitle: 'Fast start',
    featureFastDesc: 'Go from source upload to generated job results with the shortest usable product loop.',
    featureHdTitle: 'Unified asset flow',
    featureHdDesc: 'Keep panel images, storyboards, audio, video, and intermediate metadata inside one project workflow.',
    featureSmartTitle: 'Replaceable models',
    featureSmartDesc: 'Swap OCR, scripting, TTS, and video models incrementally without locking into one vendor.',
    featureAutoTitle: 'Production-oriented fork',
    featureAutoDesc: 'The current structure is designed for internal deployment, job orchestration, and model service integration.',
    aboutTitleLine1: 'AI-powered',
    aboutTitleLine2: 'comic-to-video platform',
    aboutBody1: 'The platform helps comic and webtoon teams convert static content into orchestrated video production workflows.',
    aboutBody2: 'You can build your own pipeline step by step, from upload and parsing to storyboard, voice, and final output.',
    statsVideos: 'Videos generated',
    statsUsers: 'Active users',
    statsRender: 'Avg render time',
    statsSuccess: 'Success rate',
    ctaTitle: 'Ready to start your comic video workflow?',
    ctaBody: 'Create a project, upload a PDF or CBZ, and inspect parsing, storyboard, audio, and video outputs step by step.',
    contactTitle: 'Contact us',
    contactSubtitle: 'Reach out if you need deployment help, model replacement support, or custom platform development.',
    contactFaqTitle: 'FAQ',
    contactDevTitle: 'Developers',
    contactDevSubtitle: 'If you want to collaborate, request features, or contribute, feel free to reach out.',
    loginTitle: 'Sign in to Platform',
    loginSubtitle: 'Use email/password or Google sign-in.',
    loginWithGoogle: 'Continue with Google',
    continueWithEmail: 'Continue with Email Password',
    sending: 'Sending…',
    verifying: 'Verifying…',
    verifyContinue: 'Sign In & Continue',
    backToEmail: 'Back to Sign In',
    enterCode: 'Enter your account credentials',
    authDisabledBanner: 'Authentication is currently unavailable. Check backend auth configuration first.',
    termsPrefix: 'By continuing, you agree to our',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    meetDevelopers: 'Meet the developers',
    collaborationNote: 'Feel free to reach out for collaboration or contributions.',
    registerTitle: 'Create Account',
    registerSubtitle: 'Create an account with email and password, or continue with Google.',
    emailLabel: 'Email',
    emailPlaceholder: 'Enter your email',
    usernameOrEmailLabel: 'Email or Username',
    usernameOrEmailPlaceholder: 'Enter admin, admin@local, or your email',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    displayNameLabel: 'Display Name',
    displayNamePlaceholder: 'Enter your display name',
    loginButton: 'Sign In',
    registerButton: 'Create Account',
    signingIn: 'Signing in…',
    creatingAccount: 'Creating account…',
    loginSuccessTitle: 'Signed In',
    loginSuccessBody: 'Redirecting to the platform…',
    registerSuccessTitle: 'Account Created',
    registerSuccessBody: 'Your account is ready. Entering the platform…',
    loginGenericError: 'Sign-in failed. Please try again.',
    googleSignInError: 'Google sign-in failed. Please try again.',
    loginMissingFields: 'Please enter both email and password.',
    registerMissingName: 'Please enter a display name.',
    noAccountYet: 'Need an account?',
    alreadyHaveAccount: 'Already have an account?',
    switchToRegister: 'Create one',
    switchToLogin: 'Sign in',
    googleComingSoon: 'Google sign-in will be enabled later.',
    brandName: 'Platform',
    contactNameRequired: 'Please enter your name',
    contactEmailRequired: 'Please enter your email',
    contactEmailInvalid: 'Invalid email format',
    contactMessageRequired: 'Please enter a message',
    contactSendFailed: 'Failed to send message.',
    contactSendRetry: 'Something went wrong. Please try again.',
    contactMessageSubject: 'New Message from Platform Website',
    developerFrontendRole: 'Author / Maintainer',
    developerBackendRole: 'Author / Maintainer',
    faqConvertQuestion: 'How do I convert a comic into a video?',
    faqConvertAnswer: 'Upload a PDF or CBZ source, choose a rendering mode, and start the generation flow. The platform handles parsing, storyboard generation, and video output.',
    faqFormatsQuestion: 'Which file formats are supported?',
    faqFormatsAnswer: 'The platform currently supports PDF and CBZ comic sources. Outputs can be previewed in the UI and downloaded from job assets.',
    faqPreviewQuestion: 'Can I preview results before downloading?',
    faqPreviewAnswer: 'Yes. After a job completes, you can inspect storyboards, assets, and the final video from the job detail page.',
    faqLimitQuestion: 'Is there a file size limit?',
    faqLimitAnswer: 'It is best to start with smaller test sources so upload, parsing, and generation can be validated faster.',
    faqInstallQuestion: 'Do I need extra software?',
    faqInstallAnswer: 'The frontend does not need extra software, but the backend should install ffmpeg and tesseract for fuller media capabilities.',
    faqSafetyQuestion: 'Is uploaded data safe?',
    faqSafetyAnswer: 'The platform is designed for local or internal deployment, so data handling depends on your own runtime and storage configuration.',
  },
};

export const useSiteText = () => {
  const { locale } = useLocale();
  return siteCopy[locale];
};
