import { useLocale } from '../../context/LocaleContext';

const copy = {
  zh: {
    navHome: '首页',
    navPlatform: '平台',
    navModels: '模型配置',
    navUsers: '用户管理',
    navDocs: '文档',
    navContact: '联系',
    signIn: '登录',
    loginSignup: '登录 / 注册',
    logout: '退出登录',
    loggedInAs: '当前登录',
    greeting: '你好',
    projectsBadge: '漫画视频平台',
    projectsTitle: '项目列表',
    projectsDescription: '上传 PDF 或 CBZ 漫画源文件，创建生成任务，并查看流水线各阶段产出的资产。',
    demoModeBadge: '演示模式',
    demoModeTitle: '当前正在使用 Vercel 演示前端',
    demoModeDescription: '未连接真实后端时，平台会自动使用内置 mock 数据，方便展示项目流转、分镜预览和视频结果。',
    noProjects: '还没有项目。',
    projectNamePlaceholder: '项目名称',
    supportedFormats: '支持格式：PDF、CBZ',
    createProject: '创建项目',
    creatingProject: '创建中…',
    jobsTitle: '任务列表',
    noJobs: '还没有任务，先创建一个生成任务。',
    createJob: '生成视频',
    creatingJob: '启动中…',
    renderMode: '渲染模式',
    jobStatus: '任务状态',
    progress: '进度',
    startedAt: '开始时间',
    finishedAt: '结束时间',
    notStarted: '未开始',
    started: '开始',
    finished: '完成',
    storyboard: '分镜预览',
    noStoryboard: '暂时没有分镜结果。',
    scene: '场景',
    duration: '时长',
    panels: '画格',
    subtitle: '字幕',
    narration: '旁白',
    prompt: '画面提示词',
    assets: '项目资产',
    noAssets: '暂时没有资产。',
    jobAssets: '任务资产',
    noJobAssets: '暂时没有任务资产。',
    systemStatus: '系统状态',
    modelConfigBadge: '模型配置中心',
    modelConfigTitle: '模型配置',
    modelConfigDescription: '查看当前全局默认模型提供方，并进行连通性测试或切换默认配置。',
    usersBadge: '用户管理',
    usersTitle: '用户列表',
    usersDescription: '查看后端同步的 Supabase 用户，并切换角色。',
    userEmail: '邮箱',
    userName: '名称',
    userProvider: '登录方式',
    userRole: '角色',
    userCreatedAt: '创建时间',
    userRoleUpdatedSuccess: '用户角色已更新',
    userRoleUpdateFailed: '用户角色更新失败',
    backendAuthAs: '当前后端身份',
    createProviderTitle: '新增 Provider',
    editProviderTitle: '编辑 Provider',
    cancelEditProvider: '取消编辑',
    providerTypeLabel: '能力类型',
    providerKeyLabel: 'Provider Key',
    providerDisplayNameLabel: '显示名称',
    providerBaseUrlLabel: 'Base URL',
    providerModelNameLabel: '模型名',
    providerEnabledLabel: '启用该 Provider',
    providerDefaultLabel: '设为该能力默认 Provider',
    providerConfigJsonLabel: '配置 JSON',
    applyConfigTemplate: '填入模板',
    createProviderAction: '创建 Provider',
    editProviderAction: '编辑',
    deleteProviderAction: '删除',
    saveProviderChanges: '保存修改',
    savingProvider: '保存中…',
    providerCreatedSuccess: 'Provider 创建成功',
    providerUpdatedSuccess: 'Provider 更新成功',
    providerDeletedSuccess: 'Provider 删除成功',
    providerValidationFailed: '请先修正表单校验错误',
    providerSaveFailed: 'Provider 保存失败',
    providerDeleteFailed: 'Provider 删除失败',
    providerTestSuccess: 'Provider 连通性测试成功',
    providerTestFailed: 'Provider 连通性测试失败',
    confirmDeleteProvider: '确认删除这个 Provider 吗？',
    providerKeyRequired: '请填写 Provider Key',
    providerDisplayNameRequired: '请填写显示名称',
    providerBaseUrlInvalid: 'Base URL 必须以 http:// 或 https:// 开头',
    providerConfigJsonInvalid: '配置 JSON 格式不合法',
    defaultProvider: '默认',
    enabled: '启用',
    disabled: '停用',
    setDefaultProvider: '设为默认',
    testProvider: '测试连通性',
    testingProvider: '测试中…',
    backend: '后端',
    ocr: 'OCR',
    script: '脚本',
    tts: '配音',
    video: '视频',
    ffmpeg: 'FFmpeg',
    storage: '存储',
    supabase: 'Supabase',
    activeProvider: '当前模型',
    videoResult: '视频结果',
    noVideo: '暂时还没有视频。',
    openResultArtifact: '打开结果文件',
    openNarrationAudio: '打开旁白音频',
    videoOnly: '仅视频',
    videoReady: '视频可用',
    ffmpegUnavailable: '未检测到 ffmpeg，暂未混入音轨',
    loadingJob: '任务加载中…',
    loadingProject: '项目加载中…',
    resultJsonNotice: '当前流水线返回的是 JSON 结果文件，还不是可播放视频。',
    localeSwitch: 'English',
  },
  en: {
    navHome: 'Home',
    navPlatform: 'Platform',
    navModels: 'Models',
    navUsers: 'Users',
    navDocs: 'Docs',
    navContact: 'Contact',
    signIn: 'Sign In',
    loginSignup: 'Login / Sign Up',
    logout: 'Logout',
    loggedInAs: 'Logged in as',
    greeting: 'Hi',
    projectsBadge: 'Comic Video Platform',
    projectsTitle: 'Projects',
    projectsDescription: 'Upload PDF or CBZ comic sources, create generation jobs, and inspect assets produced by each pipeline stage.',
    demoModeBadge: 'Demo Mode',
    demoModeTitle: 'The Vercel demo frontend is active',
    demoModeDescription: 'When no live backend is connected, the platform automatically falls back to built-in mock data so you can still demo projects, storyboard previews, and result playback.',
    noProjects: 'No projects yet.',
    projectNamePlaceholder: 'Project name',
    supportedFormats: 'Supported formats: PDF, CBZ',
    createProject: 'Create Project',
    creatingProject: 'Creating…',
    jobsTitle: 'Jobs',
    noJobs: 'No jobs yet. Create your first generation job.',
    createJob: 'Generate Video',
    creatingJob: 'Starting…',
    renderMode: 'Render mode',
    jobStatus: 'Job status',
    progress: 'Progress',
    startedAt: 'Started',
    finishedAt: 'Finished',
    notStarted: 'Not started',
    started: 'Started',
    finished: 'Finished',
    storyboard: 'Storyboard',
    noStoryboard: 'No storyboard yet.',
    scene: 'Scene',
    duration: 'Duration',
    panels: 'Panels',
    subtitle: 'Subtitle',
    narration: 'Narration',
    prompt: 'Video prompt',
    assets: 'Project assets',
    noAssets: 'No assets yet.',
    jobAssets: 'Job assets',
    noJobAssets: 'No job assets yet.',
    systemStatus: 'System status',
    modelConfigBadge: 'Model Config Center',
    modelConfigTitle: 'Model Configs',
    modelConfigDescription: 'Inspect the active global providers, test connectivity, and switch the default provider for each capability.',
    usersBadge: 'User Management',
    usersTitle: 'Users',
    usersDescription: 'View synced Supabase users and switch their roles.',
    userEmail: 'Email',
    userName: 'Name',
    userProvider: 'Provider',
    userRole: 'Role',
    userCreatedAt: 'Created at',
    userRoleUpdatedSuccess: 'User role updated',
    userRoleUpdateFailed: 'Failed to update user role',
    backendAuthAs: 'Backend identity',
    createProviderTitle: 'Create Provider',
    editProviderTitle: 'Edit Provider',
    cancelEditProvider: 'Cancel',
    providerTypeLabel: 'Capability Type',
    providerKeyLabel: 'Provider Key',
    providerDisplayNameLabel: 'Display Name',
    providerBaseUrlLabel: 'Base URL',
    providerModelNameLabel: 'Model Name',
    providerEnabledLabel: 'Enable this provider',
    providerDefaultLabel: 'Set as default provider for this capability',
    providerConfigJsonLabel: 'Config JSON',
    applyConfigTemplate: 'Apply template',
    createProviderAction: 'Create Provider',
    editProviderAction: 'Edit',
    deleteProviderAction: 'Delete',
    saveProviderChanges: 'Save Changes',
    savingProvider: 'Saving…',
    providerCreatedSuccess: 'Provider created successfully',
    providerUpdatedSuccess: 'Provider updated successfully',
    providerDeletedSuccess: 'Provider deleted successfully',
    providerValidationFailed: 'Please fix the form validation errors first',
    providerSaveFailed: 'Failed to save provider',
    providerDeleteFailed: 'Failed to delete provider',
    providerTestSuccess: 'Provider connectivity test succeeded',
    providerTestFailed: 'Provider connectivity test failed',
    confirmDeleteProvider: 'Delete this provider?',
    providerKeyRequired: 'Provider key is required',
    providerDisplayNameRequired: 'Display name is required',
    providerBaseUrlInvalid: 'Base URL must start with http:// or https://',
    providerConfigJsonInvalid: 'Config JSON is invalid',
    defaultProvider: 'Default',
    enabled: 'Enabled',
    disabled: 'Disabled',
    setDefaultProvider: 'Set default',
    testProvider: 'Test connectivity',
    testingProvider: 'Testing…',
    backend: 'Backend',
    ocr: 'OCR',
    script: 'Script',
    tts: 'TTS',
    video: 'Video',
    ffmpeg: 'FFmpeg',
    storage: 'Storage',
    supabase: 'Supabase',
    activeProvider: 'Active provider',
    videoResult: 'Video result',
    noVideo: 'No video yet.',
    openResultArtifact: 'Open result artifact',
    openNarrationAudio: 'Open narration audio',
    videoOnly: 'Video only',
    videoReady: 'Video ready',
    ffmpegUnavailable: 'ffmpeg unavailable, audio was not muxed',
    loadingJob: 'Loading job…',
    loadingProject: 'Loading project…',
    resultJsonNotice: 'The current pipeline returned a JSON artifact instead of a playable video.',
    localeSwitch: '中文',
  },
};

const statusMap = {
  zh: {
    QUEUED: '排队中',
    RUNNING: '运行中',
    COMPLETED: '已完成',
    FAILED: '失败',
    PENDING: '等待中',
    UPLOADED: '已上传',
  },
  en: {
    QUEUED: 'Queued',
    RUNNING: 'Running',
    COMPLETED: 'Completed',
    FAILED: 'Failed',
    PENDING: 'Pending',
    UPLOADED: 'Uploaded',
  },
};

const modeMap = {
  zh: {
    basic: '基础模式',
    hybrid: '混合模式',
  },
  en: {
    basic: 'Basic mode',
    hybrid: 'Hybrid mode',
  },
};

const assetTypeMap = {
  zh: {
    source_file: '源文件',
    parse_artifact: '解析元数据',
    panel_image: '分镜图片',
    storyboard: '分镜 JSON',
    narration_audio: '旁白音频',
    tts_artifact: '配音元数据',
    video_artifact: '中间视频',
    video_artifact_meta: '视频元数据',
    final_video: '最终视频',
    merge_artifact: '合并元数据',
    analyze_artifact: '分析结果',
    script_artifact: '脚本结果',
  },
  en: {
    source_file: 'Source file',
    parse_artifact: 'Parse metadata',
    panel_image: 'Panel image',
    storyboard: 'Storyboard JSON',
    narration_audio: 'Narration audio',
    tts_artifact: 'TTS metadata',
    video_artifact: 'Intermediate video',
    video_artifact_meta: 'Video metadata',
    final_video: 'Final video',
    merge_artifact: 'Merge metadata',
    analyze_artifact: 'Analysis artifact',
    script_artifact: 'Script artifact',
  },
};

export const usePlatformI18n = () => {
  const { locale } = useLocale();

  return {
    locale,
    t: copy[locale],
    statusLabel: (value) => statusMap[locale][value] || value,
    modeLabel: (value) => modeMap[locale][value] || value,
    assetTypeLabel: (value) => assetTypeMap[locale][value] || value,
  };
};
