import { useLocale } from '../../context/LocaleContext';

const copy = {
  zh: {
    navHome: '首页',
    navPlatform: '平台',
    navModels: '模型配置',
    navUsers: '用户管理',
    navDocs: '文档',
    navContact: '联系',
    signIn: '登录',
    loginSignup: '登录 / 注册',
    logout: '退出登录',
    loggedInAs: '当前登录',
    greeting: '你好',
    projectsBadge: '漫画视频平台',
    projectsTitle: '项目列表',
    projectsDescription: '上传 PDF 或 CBZ 漫画源文件，创建生成任务，并查看流水线各阶段产出的资产。',
    demoModeBadge: '演示模式',
    demoModeTitle: '当前正在使用 Vercel 演示前端',
    demoModeDescription: '未连接真实后端时，平台会自动使用内置 mock 数据，方便展示项目流转、分镜预览和视频结果。',
    noProjects: '还没有项目。',
    projectNamePlaceholder: '项目名称',
    supportedFormats: '支持格式：PDF、CBZ',
    createProject: '创建项目',
    creatingProject: '创建中…',
    jobsTitle: '任务列表',
    noJobs: '还没有任务，先创建一个生成任务。',
    createJob: '生成视频',
    creatingJob: '启动中…',
    renderMode: '渲染模式',
    jobStatus: '任务状态',
    progress: '进度',
    startedAt: '开始时间',
    finishedAt: '结束时间',
    notStarted: '未开始',
    started: '开始',
    finished: '完成',
    storyboard: '分镜预览',
    noStoryboard: '暂时没有分镜结果。',
    scene: '场景',
    duration: '时长',
    panels: '画格',
    subtitle: '字幕',
    narration: '旁白',
    prompt: '画面提示词',
    assets: '项目资产',
    noAssets: '暂时没有资产。',
    jobAssets: '任务资产',
    noJobAssets: '暂时没有任务资产。',
    systemStatus: '系统状态',
    modelConfigBadge: '模型配置',
    modelConfigTitle: '模型与供应商配置',
    modelConfigDescription: '为各类能力配置云供应商、本地服务和具体模型实例，支持一个 API 地址下挂多个模型。',
    usersBadge: '用户管理',
    usersTitle: '用户列表',
    usersDescription: '查看后端同步的本地账户用户，并切换角色。',
    userEmail: '邮箱',
    userName: '名称',
    userProvider: '登录方式',
    userRole: '角色',
    userCreatedAt: '创建时间',
    userRoleUpdatedSuccess: '用户角色已更新',
    userRoleUpdateFailed: '用户角色更新失败',
    backendAuthAs: '当前后端身份',
    createProviderTitle: '新增模型配置',
    editProviderTitle: '编辑模型配置',
    cancelEditProvider: '取消编辑',
    providerTypeLabel: '能力类型',
    providerKeyLabel: '供应商标识',
    providerDisplayNameLabel: '配置名称',
    providerBaseUrlLabel: 'API 地址',
    providerModelNameLabel: '模型名称',
    providerEnabledLabel: '启用该模型配置',
    providerDefaultLabel: '设为该能力的默认模型',
    providerConfigJsonLabel: '配置 JSON',
    applyConfigTemplate: '填入模板',
    createProviderAction: '新增模型配置',
    editProviderAction: '编辑',
    deleteProviderAction: '删除',
    saveProviderChanges: '保存修改',
    savingProvider: '保存中…',
    providerCreatedSuccess: '模型提供方创建成功',
    providerUpdatedSuccess: '模型提供方更新成功',
    providerDeletedSuccess: '模型提供方删除成功',
    providerValidationFailed: '请先修正表单校验错误',
    providerSaveFailed: '模型提供方保存失败',
    providerDeleteFailed: '模型提供方删除失败',
    providerTestSuccess: '模型配置连通性测试成功',
    providerTestFailed: '模型配置连通性测试失败',
    confirmDeleteProvider: '确认删除这个模型配置吗？',
    searchProvidersPlaceholder: '搜索名称、标识或模型名',
    filterAllTypes: '全部类型',
    noFilteredProviders: '当前筛选条件下没有模型提供方。',
    clearFiltersAction: '清空筛选',
    viewDetailsAction: '查看详情',
    hideConfigAction: '收起配置',
    showConfigAction: '查看配置',
    testResultTitle: '测试结果',
    rawResponseLabel: '原始响应',
    providerLabel: '供应商',
    typeLabel: '类型',
    closeAction: '关闭',
    successStatus: '成功',
    failedStatus: '失败',
    emptyProvidersHint: '先新增一个模型服务，然后在这里测试、设默认、编辑配置。',
    notTestedStatus: '未测试',
    lastTestStatusLabel: '最近测试',
    defaultHint: '当前默认提供方',
    endpointNotConfigured: '未配置服务地址',
    modelNotConfigured: '未配置模型名称',
    lastTestAtLabel: '最近测试时间',
    neverTestedAtLabel: '尚未测试',
    sortProvidersLabel: '排序方式',
    sortDefaultFirst: '默认优先',
    sortLastTested: '最近测试',
    sortNameAsc: '名称 A-Z',
    bulkTestAction: '批量测试当前结果',
    bulkTestingAction: '批量测试中…',
    bulkTestSummary: '批量测试完成：成功 {successCount} 个，失败 {failedCount} 个。',
    refreshListAction: '刷新列表',
    configSectionHint: '按需展开查看详细运行参数。',
    providerKeyRequired: '请填写提供方标识',
    providerDisplayNameRequired: '请填写显示名称',
    providerBaseUrlInvalid: '服务地址必须以 http:// 或 https:// 开头',
    providerConfigJsonInvalid: '配置 JSON 格式不合法',
    defaultProvider: '默认模型',
    enabled: '启用',
    disabled: '停用',
    setDefaultProvider: '设为默认',
    testProvider: '测试连通性',
    testingProvider: '测试中…',
    backend: '后端',
    ocr: 'OCR',
    script: '脚本',
    tts: '配音',
    video: '视频',
    ffmpeg: 'FFmpeg',
    storage: '存储',
    activeProvider: '当前模型',
    videoResult: '视频结果',
    noVideo: '暂时还没有视频。',
    openResultArtifact: '打开结果文件',
    openNarrationAudio: '打开旁白音频',
    videoOnly: '仅视频',
    videoReady: '视频可用',
    ffmpegUnavailable: '未检测到 ffmpeg，暂未混入音轨',
    loadingJob: '任务加载中…',
    loadingProject: '项目加载中…',
    resultJsonNotice: '当前流水线返回的是 JSON 结果文件，还不是可播放视频。',
    localeSwitch: 'English',
    projectsCountLabel: '项目数',
    projectsMetricTitle: '项目数',
    projectsCountHint: '已上传漫画源文件',
    backendStatusLabel: '后端',
    backendStatusHint: '系统心跳',
    systemStatusDescription: '运行健康、模型提供方接线状态与本地工具可用性。',
    loadingSystemStatus: '系统状态加载中…',
    loadingProjects: '项目加载中…',
    projectsLoadFailed: '项目加载失败。',
    systemStatusLoadFailed: '系统状态加载失败。',
    providerLoadFailed: '模型提供方加载失败。',
    projectsBrowseDescription: '浏览已有项目、查看源文件，并继续后续生成流程。',
    refreshAction: '刷新',
    cleanupEmptyProjectsAction: '清理空项目',
    cleaningEmptyProjectsAction: '清理中…',
    cleanupEmptyProjectsSuccess: '空项目已清理。',
    cleanupEmptyProjectsFailed: '清理空项目失败。',
    createProjectTitle: '创建项目',
    createProjectDescription: '上传 PDF 或 CBZ 源文件，启动新的处理流程。',
    uploadValidationError: '请填写项目名称并选择源文件。',
    projectCreateFailed: '创建项目失败。',
    sourceFileLabel: '源文件',
    noFileSelected: '暂未选择文件',
    ready: '可用',
    missing: '缺失',
    notDetected: '未检测到',
    unknown: '未知',
    usersAdminBadge: '管理',
    usersCountLabel: '位用户',
    loadingUsers: '用户加载中…',
    usersLoadFailed: '用户加载失败。',
    noUsersFound: '暂无用户。',
    usersListTitle: '用户列表',
    usersListDescription: '当前页面需要管理员权限；如果接口返回 401，请重新登录管理员账号。',
    userStatus: '状态',
    providerInventoryTitle: '模型配置列表',
    providerInventoryDescription: '查看每类能力下的供应商、API 地址、模型实例与默认模型。',
    loadingProviders: '模型提供方加载中…',
    noProvidersFound: '暂未配置任何模型提供方。',
    providersCountLabel: '个提供方',
    formHintModelConfig: '支持配置云供应商、本地服务和同一 API 下的多个模型实例，并直接查看与编辑高级 JSON 配置。',
    setDefaultAction: '设为默认模型',
    editAction: '编辑',
    deleteAction: '删除',
    modelLabel: '模型',
    endpointLabel: '地址',
    providerTestPassed: '模型配置测试通过。',
    providerTestFailedMessage: '模型配置测试失败。',
    vendorSectionTitle: '供应商',
    modelSectionTitle: '模型实例',
    capabilityMappingTitle: '能力映射',
    capabilityMappingHint: '把当前供应商下的某个模型实例映射到业务能力，例如 script、ocr、tts、video。',
    vendorConnectionTitle: '供应商连接',
    vendorConnectionHint: '先配置供应商连接与认证，再从该连接下拉取模型列表。',
    vendorKeyHint: '例如 openai_compatible、azure_openai、openrouter、paddleocr',
    configNameHint: '给这条模型配置起一个便于团队识别的名字',
    baseUrlHint: '同一个供应商地址下可以挂多个模型实例',
    modelNameHint: '例如 gpt-4o-mini、deepseek-chat、paddleocr-v4',
    cloudModelHint: '适合云 API、多模型网关和本地统一推理服务。',
    vendorTemplateLabel: '供应商模板',
    vendorTemplateHint: '先选择常用供应商模板，再按需微调地址、模型名和高级配置。',
    customTemplateOption: '自定义',
    recommendedOptionSuffix: '（推荐）',
    apiKeyLabel: 'API Key',
    apiKeyHint: '优先支持 OpenAI-compatible 接口，填写后可直接通过 /models 获取模型列表。',
    discoverModelsAction: '获取模型列表',
    discoveringModelsAction: '获取中…',
    discoveredModelsLabel: '可用模型',
    discoveredModelsHint: '从 OpenAI-compatible /models 接口返回的模型列表中选择',
    modelDiscoverySuccess: '模型列表获取成功',
    modelDiscoveryFailed: '模型列表获取失败',
    openAICompatibleFlowHint: '推荐优先接入 OpenAI-compatible 云模型或兼容网关：填 API 地址、填 Key、获取模型、再保存。',
    endpointGroupTitle: '供应商连接',
    modelInstanceTitle: '模型实例',
    endpointUnavailableHint: '未配置 API 地址',
    vendorConfigCardHint: '同一个供应商地址下可保存多条模型配置',
    docsBadge: '文档',
    platformFooterDescription: '一个面向漫画转视频工作流的平台，用于上传 PDF / CBZ 源文件、创建任务、检查生成资产，并持续迭代到完整旁白视频。',
    quickLinks: '快速链接',
    repository: '代码仓库',
    userManagementTitle: '用户管理',
    usersPageDescription: '查看当前本地用户、角色和状态。这里优先保证能看清数据与错误状态，再逐步补充编辑能力。',
    dashPlaceholder: '—',
    sourceSuffix: '源文件',
    jobDetailLoadFailed: '任务详情加载失败。',
    projectDetailLoadFailed: '项目详情加载失败。',
    projectHeaderTitle: '项目详情',
    jobHeaderTitle: '任务详情',
    modeLabelTitle: '模式',
    languageLabel: '语言',
    voiceLabel: '音色',
    subtitlesLabel: '字幕',
    subtitlesOn: '开启',
    subtitlesOff: '关闭',
    assetCountSuffix: '项',
    workspaceFlowTitle: '工作流总览',
    workspaceFlowDashboardDescription: '用更接近主流平台的方式，把上传、任务、分镜和结果集中到一个工作区里。',
    workspaceFlowProjectDescription: '围绕单个项目集中查看源文件、任务、分镜产物与最终结果。',
    executionWorkspaceTitle: '执行工作区',
    executionWorkspaceDescription: '围绕任务执行过程集中查看步骤、分镜、产物和最终视频结果。',
    activeProjectTitle: '当前项目',
    activeJobTitle: '当前任务',
    activeStepTitle: '当前步骤',
    openWorkspaceAction: '打开工作区',
    readyServicesTitle: '就绪服务',
    readyServicesHint: '模型链路可用状态',
    queuedLabel: '排队中',
    processingLabel: '处理中',
    completedLabel: '已完成',
    runHistoryTitle: '运行历史',
    runHistoryHint: '任务每一次执行都会保留',
    activeRunTitle: '当前运行',
    runWorkspaceHint: '切换运行可查看该次执行的步骤与产物。',
    runArtifactsVersionHint: '当前仅展示所选运行的产物；同一步骤重复执行会保留历史版本。',
    executionStepsDescription: '查看每个步骤的状态、错误和重跑操作。',
    jobAssetsDescription: '每个步骤输出的产物都可以在这里查看。',
    storyboardDescription: '分镜结果会在这里展示。',
    videoResultDescription: '最终视频结果与元数据。',
    resumeAction: '继续执行',
    rerunAction: '重跑',
    resumeTitle: '继续执行这次运行？',
    rerunTitle: '重跑这次运行？',
    resumeJobHint: '将基于最近一次运行继续执行。',
    rerunJobHint: '将创建新的执行运行并重新开始。',
    resumeFromStepHint: '从该步骤继续',
    rerunFromStepHint: '从该步骤重跑',
    confirmAction: '确认',
    cancelAction: '取消',
    projectAssetsTitle: '项目资产',
    projectAssetsDescription: '源文件、解析结果和后续生成产物都会逐步沉淀在这里。',
    jobsWorkspaceDescription: '从这里进入每个任务的详细执行页，查看状态、分镜和结果。',
    activePipelineRunsHint: '活跃流水线任务',
    generatedArtifactsHint: '已生成资产数量',
    finishedJobsHint: '已完成任务数',
    pipelineCompletionHint: '流水线完成进度',
    executionNodesHint: '执行节点数量',
    generatedArtifactsLabelHint: '生成产物数量',
    executionStepsTitle: '执行步骤',
    noActiveStep: '当前还没有活跃步骤。',
    pipelineStepFallback: '流水线步骤',
    startTimeLabel: '开始',
    endTimeLabel: '结束',
    reusedStepLabel: '复用结果',
    reusedFromLabel: '复用自历史步骤',
    assetFilterAll: '全部资产',
    assetFilterLatest: '仅看最新',
    assetFilterStepAll: '全部步骤',
    rerunImpactHint: '将创建新的运行记录；目标步骤及后续步骤会重新执行，之前成功产物仍会保留。',
    resumeImpactHint: '将优先复用之前已成功的步骤结果，仅从指定节点继续。',
    runSummaryTitle: '运行摘要',
    executedStepsLabel: '实际执行步骤',
    reusedStepsCountLabel: '复用步骤',
    failedStepLabel: '失败步骤',
    openStepDetailsAction: '查看详情',
    stepInputTitle: '步骤输入',
    stepOutputTitle: '步骤输出',
    noStepPayload: '当前步骤暂无输入或输出内容。',
    closeAction: '关闭',
    sourceRunLabel: '来源运行',
    sourceStepRunLabel: '来源步骤记录',
    sourceStepLabel: '来源步骤',
    copiedJsonMessage: 'JSON 已复制',
    copyJsonAction: '复制 JSON',
    runBadgeExecuted: '实跑',
    runBadgeReused: '复用',
    lastUpdatedLabel: '最近更新',
    runAssetsLabel: '运行产物',
    noFailedStep: '无失败',
    },
  en: {
    navHome: 'Home',
    navPlatform: 'Platform',
    navModels: 'Models',
    navUsers: 'Users',
    navDocs: 'Docs',
    navContact: 'Contact',
    signIn: 'Sign In',
    loginSignup: 'Login / Sign Up',
    logout: 'Logout',
    loggedInAs: 'Logged in as',
    greeting: 'Hi',
    projectsBadge: 'Comic Video Platform',
    projectsTitle: 'Projects',
    projectsDescription: 'Upload PDF or CBZ comic sources, create generation jobs, and inspect assets produced by each pipeline stage.',
    demoModeBadge: 'Demo Mode',
    demoModeTitle: 'The Vercel demo frontend is active',
    demoModeDescription: 'When no live backend is connected, the platform automatically falls back to built-in mock data so you can still demo projects, storyboard previews, and result playback.',
    noProjects: 'No projects yet.',
    projectNamePlaceholder: 'Project name',
    supportedFormats: 'Supported formats: PDF, CBZ',
    createProject: 'Create Project',
    creatingProject: 'Creating…',
    jobsTitle: 'Jobs',
    noJobs: 'No jobs yet. Create your first generation job.',
    createJob: 'Generate Video',
    creatingJob: 'Starting…',
    renderMode: 'Render mode',
    jobStatus: 'Job status',
    progress: 'Progress',
    startedAt: 'Started',
    finishedAt: 'Finished',
    notStarted: 'Not started',
    started: 'Started',
    finished: 'Finished',
    storyboard: 'Storyboard',
    noStoryboard: 'No storyboard yet.',
    scene: 'Scene',
    duration: 'Duration',
    panels: 'Panels',
    subtitle: 'Subtitle',
    narration: 'Narration',
    prompt: 'Video prompt',
    assets: 'Project assets',
    noAssets: 'No assets yet.',
    jobAssets: 'Job assets',
    noJobAssets: 'No job assets yet.',
    systemStatus: 'System status',
    modelConfigBadge: 'Model Config Center',
    modelConfigTitle: 'Models & Vendor Configs',
    modelConfigDescription: 'Configure cloud vendors, local services, and concrete model instances for each capability, including multiple models under one API endpoint.',
    usersBadge: 'User Management',
    usersTitle: 'Users',
    usersDescription: 'View synced local account users and switch their roles.',
    userEmail: 'Email',
    userName: 'Name',
    userProvider: 'Provider',
    userRole: 'Role',
    userCreatedAt: 'Created at',
    userRoleUpdatedSuccess: 'User role updated',
    userRoleUpdateFailed: 'Failed to update user role',
    backendAuthAs: 'Backend identity',
    createProviderTitle: 'Create Model Config',
    editProviderTitle: 'Edit Model Config',
    cancelEditProvider: 'Cancel',
    providerTypeLabel: 'Capability Type',
    providerKeyLabel: 'Vendor Key',
    providerDisplayNameLabel: 'Config Name',
    providerBaseUrlLabel: 'API Endpoint',
    providerModelNameLabel: 'Model Name',
    providerEnabledLabel: 'Enable this model config',
    providerDefaultLabel: 'Set as the default model for this capability',
    providerConfigJsonLabel: 'Config JSON',
    applyConfigTemplate: 'Apply template',
    createProviderAction: 'Create Model Config',
    editProviderAction: 'Edit',
    deleteProviderAction: 'Delete',
    saveProviderChanges: 'Save Changes',
    savingProvider: 'Saving…',
    providerCreatedSuccess: 'Provider created successfully',
    providerUpdatedSuccess: 'Provider updated successfully',
    providerDeletedSuccess: 'Provider deleted successfully',
    providerValidationFailed: 'Please fix the form validation errors first',
    providerSaveFailed: 'Failed to save provider',
    providerDeleteFailed: 'Failed to delete provider',
    providerTestSuccess: 'Model config connectivity test succeeded',
    providerTestFailed: 'Model config connectivity test failed',
    confirmDeleteProvider: 'Delete this model config?',
    searchProvidersPlaceholder: 'Search name, key, or model',
    filterAllTypes: 'All types',
    noFilteredProviders: 'No providers match the current filters.',
    clearFiltersAction: 'Clear filters',
    viewDetailsAction: 'View details',
    hideConfigAction: 'Hide config',
    showConfigAction: 'View config',
    testResultTitle: 'Test result',
    rawResponseLabel: 'Raw response',
    providerLabel: 'Vendor',
    typeLabel: 'Type',
    closeAction: 'Close',
    successStatus: 'Success',
    failedStatus: 'Failed',
    emptyProvidersHint: 'Create a provider first, then test it, set a default, or edit its configuration here.',
    notTestedStatus: 'Not tested',
    lastTestStatusLabel: 'Last test',
    defaultHint: 'Current default provider',
    endpointNotConfigured: 'Endpoint not configured',
    modelNotConfigured: 'Model not configured',
    lastTestAtLabel: 'Last tested at',
    neverTestedAtLabel: 'Never tested',
    sortProvidersLabel: 'Sort by',
    sortDefaultFirst: 'Default first',
    sortLastTested: 'Recently tested',
    sortNameAsc: 'Name A-Z',
    bulkTestAction: 'Test current results',
    bulkTestingAction: 'Bulk testing…',
    bulkTestSummary: 'Bulk testing finished: {successCount} succeeded, {failedCount} failed.',
    refreshListAction: 'Refresh list',
    configSectionHint: 'Expand when you need to inspect runtime parameters.',
    providerKeyRequired: 'Provider key is required',
    providerDisplayNameRequired: 'Display name is required',
    providerBaseUrlInvalid: 'Base URL must start with http:// or https://',
    providerConfigJsonInvalid: 'Config JSON is invalid',
    defaultProvider: 'Default Model',
    enabled: 'Enabled',
    disabled: 'Disabled',
    setDefaultProvider: 'Set default',
    testProvider: 'Test connectivity',
    testingProvider: 'Testing…',
    backend: 'Backend',
    ocr: 'OCR',
    script: 'Script',
    tts: 'TTS',
    video: 'Video',
    ffmpeg: 'FFmpeg',
    storage: 'Storage',
    activeProvider: 'Active provider',
    videoResult: 'Video result',
    noVideo: 'No video yet.',
    openResultArtifact: 'Open result artifact',
    openNarrationAudio: 'Open narration audio',
    videoOnly: 'Video only',
    videoReady: 'Video ready',
    ffmpegUnavailable: 'ffmpeg unavailable, audio was not muxed',
    loadingJob: 'Loading job…',
    loadingProject: 'Loading project…',
    resultJsonNotice: 'The current pipeline returned a JSON artifact instead of a playable video.',
    localeSwitch: '中文',
    projectsCountLabel: 'Projects',
    projectsMetricTitle: 'Projects',
    projectsCountHint: 'Uploaded comic sources',
    backendStatusLabel: 'Backend',
    backendStatusHint: 'System heartbeat',
    systemStatusDescription: 'Runtime health, provider wiring, and local tool availability.',
    loadingSystemStatus: 'Loading system status…',
    loadingProjects: 'Loading projects…',
    projectsLoadFailed: 'Failed to load projects.',
    systemStatusLoadFailed: 'Failed to load system status.',
    providerLoadFailed: 'Failed to load model providers.',
    projectsBrowseDescription: 'Browse existing projects, inspect their source files, and continue generation work.',
    refreshAction: 'Refresh',
    cleanupEmptyProjectsAction: 'Clean Empty Projects',
    cleaningEmptyProjectsAction: 'Cleaning…',
    cleanupEmptyProjectsSuccess: 'Empty projects cleaned.',
    cleanupEmptyProjectsFailed: 'Failed to clean empty projects.',
    createProjectTitle: 'Create Project',
    createProjectDescription: 'Upload a PDF or CBZ source file and start a new processing pipeline.',
    uploadValidationError: 'Please provide a project name and choose a source file.',
    projectCreateFailed: 'Failed to create project.',
    sourceFileLabel: 'Source File',
    noFileSelected: 'No file selected yet',
    ready: 'Ready',
    missing: 'Missing',
    notDetected: 'Not detected',
    unknown: 'Unknown',
    usersAdminBadge: 'Admin',
    usersCountLabel: 'users',
    loadingUsers: 'Loading users…',
    usersLoadFailed: 'Failed to load users.',
    noUsersFound: 'No users found.',
    usersListTitle: 'User List',
    usersListDescription: 'This page requires admin access; if the API returns 401, sign in again with the admin account.',
    userStatus: 'Status',
    providerInventoryTitle: 'Model Config Inventory',
    providerInventoryDescription: 'Review vendors, endpoints, model instances, and default model choices for each capability.',
    loadingProviders: 'Loading model providers…',
    noProvidersFound: 'No model providers configured yet.',
    providersCountLabel: 'providers',
    formHintModelConfig: 'Configure cloud vendors, local services, and multiple model instances behind the same API endpoint with advanced JSON options.',
    setDefaultAction: 'Set as Default Model',
    editAction: 'Edit',
    deleteAction: 'Delete',
    modelLabel: 'Model',
    endpointLabel: 'Endpoint',
    providerTestPassed: 'Model config test passed.',
    providerTestFailedMessage: 'Model config test failed.',
    vendorSectionTitle: 'Vendor',
    modelSectionTitle: 'Model Instance',
    capabilityMappingTitle: 'Capability Mapping',
    capabilityMappingHint: 'Map a model instance from the current vendor connection to a business capability such as script, ocr, tts, or video.',
    vendorConnectionTitle: 'Vendor Connection',
    vendorConnectionHint: 'Configure the vendor connection and authentication first, then fetch models from that connection.',
    vendorKeyHint: 'For example openai_compatible, azure_openai, openrouter, paddleocr',
    configNameHint: 'Use a team-friendly name for this config',
    baseUrlHint: 'One vendor endpoint can host multiple model instances',
    modelNameHint: 'For example gpt-4o-mini, deepseek-chat, paddleocr-v4',
    cloudModelHint: 'Ideal for cloud APIs, multi-model gateways, and local unified inference services.',
    vendorTemplateLabel: 'Vendor Template',
    vendorTemplateHint: 'Start from a common vendor preset, then fine-tune the endpoint, model name, and advanced config.',
    customTemplateOption: 'Custom',
    recommendedOptionSuffix: ' (Recommended)',
    apiKeyLabel: 'API Key',
    apiKeyHint: 'Optimized for OpenAI-compatible APIs. Fill it in to fetch models directly from /models.',
    discoverModelsAction: 'Fetch Models',
    discoveringModelsAction: 'Fetching…',
    discoveredModelsLabel: 'Available Models',
    discoveredModelsHint: 'Choose from the model list returned by the OpenAI-compatible /models endpoint',
    modelDiscoverySuccess: 'Model list fetched successfully',
    modelDiscoveryFailed: 'Failed to fetch model list',
    openAICompatibleFlowHint: 'Recommended flow: connect an OpenAI-compatible cloud API or gateway, add the endpoint, add the key, fetch models, then save.',
    endpointGroupTitle: 'Vendor Connection',
    modelInstanceTitle: 'Model Instance',
    endpointUnavailableHint: 'No API endpoint configured',
    vendorConfigCardHint: 'You can keep multiple model configs under the same vendor endpoint',
    docsBadge: 'Docs',
    platformFooterDescription: 'A comic-to-video workflow platform for uploading PDF and CBZ sources, creating jobs, inspecting generated assets, and iterating toward a full narrated video pipeline.',
    quickLinks: 'Quick Links',
    repository: 'Repository',
    userManagementTitle: 'User Management',
    usersPageDescription: 'Review local users, roles, and statuses. This page currently prioritizes visibility and clear failure states before editing features.',
    dashPlaceholder: '—',
    sourceSuffix: 'source',
    jobDetailLoadFailed: 'Failed to load job details.',
    projectDetailLoadFailed: 'Failed to load project details.',
    projectHeaderTitle: 'Project Detail',
    jobHeaderTitle: 'Job Detail',
    modeLabelTitle: 'Mode',
    languageLabel: 'Language',
    voiceLabel: 'Voice',
    subtitlesLabel: 'Subtitles',
    subtitlesOn: 'On',
    subtitlesOff: 'Off',
    assetCountSuffix: 'items',
    workspaceFlowTitle: 'Workspace Flow',
    workspaceFlowDashboardDescription: 'Bring uploads, jobs, storyboards, and results into a workspace that feels closer to modern platforms.',
    workspaceFlowProjectDescription: 'Keep source files, jobs, storyboard artifacts, and final results together for a single project.',
    executionWorkspaceTitle: 'Execution Workspace',
    executionWorkspaceDescription: 'Review steps, storyboard data, artifacts, and the final video result in one place.',
    activeProjectTitle: 'Active Project',
    activeJobTitle: 'Active Job',
    activeStepTitle: 'Active Step',
    openWorkspaceAction: 'Open Workspace',
    readyServicesTitle: 'Ready Services',
    readyServicesHint: 'Model pipeline availability',
    queuedLabel: 'Queued',
    processingLabel: 'Processing',
    completedLabel: 'Completed',
    runHistoryTitle: 'Run History',
    runHistoryHint: 'Every execution is preserved',
    activeRunTitle: 'Current Run',
    runWorkspaceHint: 'Switch runs to review that execution’s steps and artifacts.',
    runArtifactsVersionHint: 'This view only shows artifacts from the selected run; repeated step executions keep historical versions.',
    executionStepsDescription: 'Review each step’s status, errors, and rerun actions.',
    jobAssetsDescription: 'Artifacts produced by each step appear here.',
    storyboardDescription: 'Storyboard results appear here.',
    videoResultDescription: 'Final video result and metadata.',
    resumeAction: 'Resume',
    rerunAction: 'Rerun',
    resumeTitle: 'Resume this run?',
    rerunTitle: 'Rerun this run?',
    resumeJobHint: 'Continue from the most recent run.',
    rerunJobHint: 'Create a new run and start again.',
    resumeFromStepHint: 'Resume from step',
    rerunFromStepHint: 'Rerun from step',
    confirmAction: 'Confirm',
    cancelAction: 'Cancel',
    projectAssetsTitle: 'Project Assets',
    projectAssetsDescription: 'Source files, parse outputs, and later generated artifacts accumulate here over time.',
    jobsWorkspaceDescription: 'Open each job detail page from here to inspect status, storyboard data, and outputs.',
    activePipelineRunsHint: 'Active pipeline runs',
    generatedArtifactsHint: 'Generated project artifacts',
    finishedJobsHint: 'Finished jobs',
    pipelineCompletionHint: 'Pipeline completion',
    executionNodesHint: 'Execution nodes',
    generatedArtifactsLabelHint: 'Generated artifacts',
    executionStepsTitle: 'Execution Steps',
    noActiveStep: 'No active step yet.',
    pipelineStepFallback: 'Pipeline Step',
    startTimeLabel: 'Start',
    endTimeLabel: 'End',
    reusedStepLabel: 'Reused',
    reusedFromLabel: 'Reused from history',
    assetFilterAll: 'All assets',
    assetFilterLatest: 'Latest only',
    assetFilterStepAll: 'All steps',
    rerunImpactHint: 'This creates a new run; the target step and downstream steps execute again while previous successful artifacts are retained.',
    resumeImpactHint: 'This prefers previously successful step outputs and continues only from the selected point.',
    runSummaryTitle: 'Run Summary',
    executedStepsLabel: 'Executed Steps',
    reusedStepsCountLabel: 'Reused Steps',
    failedStepLabel: 'Failed Step',
    openStepDetailsAction: 'View Details',
    stepInputTitle: 'Step Input',
    stepOutputTitle: 'Step Output',
    noStepPayload: 'This step does not have input or output content yet.',
    closeAction: 'Close',
    sourceRunLabel: 'Source Run',
    sourceStepRunLabel: 'Source Step Run',
    sourceStepLabel: 'Source Step',
    copiedJsonMessage: 'JSON copied',
    copyJsonAction: 'Copy JSON',
    runBadgeExecuted: 'Executed',
    runBadgeReused: 'Reused',
    lastUpdatedLabel: 'Updated',
    runAssetsLabel: 'Run Assets',
    noFailedStep: 'No failures',
  },
};

const statusMap = {
  zh: {
    QUEUED: '排队中',
    RUNNING: '运行中',
    COMPLETED: '已完成',
    FAILED: '失败',
    PENDING: '等待中',
    UPLOADED: '已上传',
  },
  en: {
    QUEUED: 'Queued',
    RUNNING: 'Running',
    COMPLETED: 'Completed',
    FAILED: 'Failed',
    PENDING: 'Pending',
    UPLOADED: 'Uploaded',
  },
};

const modeMap = {
  zh: {
    basic: '基础模式',
    hybrid: '混合模式',
  },
  en: {
    basic: 'Basic mode',
    hybrid: 'Hybrid mode',
  },
};

const assetTypeMap = {
  zh: {
    source_file: '源文件',
    parse_artifact: '解析元数据',
    panel_image: '分镜图片',
    storyboard: '分镜 JSON',
    narration_audio: '旁白音频',
    tts_artifact: '配音元数据',
    video_artifact: '中间视频',
    video_artifact_meta: '视频元数据',
    final_video: '最终视频',
    merge_artifact: '合并元数据',
    analyze_artifact: '分析结果',
    script_artifact: '脚本结果',
  },
  en: {
    source_file: 'Source file',
    parse_artifact: 'Parse metadata',
    panel_image: 'Panel image',
    storyboard: 'Storyboard JSON',
    narration_audio: 'Narration audio',
    tts_artifact: 'TTS metadata',
    video_artifact: 'Intermediate video',
    video_artifact_meta: 'Video metadata',
    final_video: 'Final video',
    merge_artifact: 'Merge metadata',
    analyze_artifact: 'Analysis artifact',
    script_artifact: 'Script artifact',
  },
};

export const usePlatformI18n = () => {
  const { locale } = useLocale();

  return {
    locale,
    t: copy[locale],
    statusLabel: (value) => statusMap[locale][value] || value,
    modeLabel: (value) => modeMap[locale][value] || value,
    assetTypeLabel: (value) => assetTypeMap[locale][value] || value,
  };
};
