version: "3.9"

services:
  paddleocr-vllm:
    image: 681a696ead69
    container_name: paddleocr-vllm-server
    user: root
    privileged: true
    devices:
      - /dev/kfd
      - /dev/dri
      - /dev/mkfd
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - /opt/hyhal/:/opt/hyhal/:ro
      - /root/models/PaddlePaddle/PaddleOCR-VL:/home/paddleocr/.paddlex/official_models/PaddleOCR-VL-1.5
    environment:
      HIP_VISIBLE_DEVICES: "0,1"
      PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK: "True"
    shm_size: "64g"
    network_mode: "host"
    command: >
      paddleocr genai_server
        --model_name PaddleOCR-VL-1.5-0.9B
        --host 0.0.0.0
        --port 8118
        --backend vllm
